### ISSUE TITLE
dumpctl produces invalid JSON text INSERT statements

### ISSUE THREAD

**Issue by cfaloon** [jbielick/dumpctl#2]
## Problem
I have an application that stores serialized objects in JSON columns. The resulting insert statements produced by `dumpctl` contains unescaped quotation marks and newlines. I understand the serialized encoding of an object in the database for my application is a little questionable, but a string value should be valid JSON.

## Steps to reproduce
1. Create a table with a JSON column
```
create table test(
  `col` json
)
```
2. Add a row to the table containing quoted strings, and newlines:
```
INSERT INTO `test` (`col`) VALUES
('\"--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess\\nkey1: value1\\nkey2: value2\\n\"');
```
3. Use `dumpctl` with a minimal configuration file to dump the contents of the `test` table.
```
database "dumptest" {
  table "test" {
  }
}
```
4. Try to import using the generated statements, receive error:
`Query 1 ERROR: Invalid JSON text: "Invalid encoding in string." at position 56 in value for column 'test.col'.`

**Comment by jbielick** [comment]
This should be resolved ([and tested](https://github.com/jbielick/dumpctl/tree/main/tests/0001-escaping)) in v0.6.0
